# Generated by Django 5.2.10 on 2026-04-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designer',
            name='initials',
        ),
        migrations.AddField(
            model_name='designer',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='designer',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='designer',
            name='profession',
            field=models.CharField(choices=[('architect', 'Architect'), ('structural_engineer', 'Structural Engineer'), ('mechanical_engineer', 'Mechanical Engineer'), ('electrical_engineer', 'Electrical Engineer'), ('interior_designer', 'Interior Designer')], max_length=100),
        ),
        migrations.AlterField(
            model_name='designer',
            name='short_bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
